### PR TITLE
added IndexedDBShim detection closes #58

### LINKED ISSUE #58: Please detect IndexedDBShim if indexedDB is not defined.

### PR DESCRIPTION
**Pull request by JamesKyburz**
This can be handy if you have to use the IndexedDBShim.

Eg iOS 8 homescreen mode where window.indexedDB is null + readonly!

### CODE REVIEW

**Comment by jensarps** [comment]
Thanks for the PR!

That's a reasonable addition, will merge this.

**Comment by JamesKyburz** [comment]
Thanks! Then I can push for level-js using the updated version and remove my hack ;)

**Comment by JamesKyburz** [comment]
Any chance this can be merged soon? Thanks

**Comment by jensarps** [comment]
Done, available in 1.5 https://github.com/jensarps/IDBWrapper/tree/v1.5

**Comment by JamesKyburz** [comment]
Great thanks!

**Comment by jensarps** [comment]
Anytime, thanks for the PR in the first place :)

**Pull request merged**
