### PR TITLE
Fixed Null Error Response : getBatch and False Positive Error thrown from Batch function

### PR DESCRIPTION
**Pull request by jayfunk**
-Added a fix to getBatch where the onError callback is called with a null error message when an empty array of keys is passed to the function. Now in the case of an empty array the getBatch function will short circuit with calling onSuccess with an empty array of results.

-Added node_modules to .gitignore

-Added a short circuit for the batch function that performs batching for removeBatch, putBatch, and upsertBatch. This function provided with an empty array of items will result in an error.

### CODE REVIEW

**Comment by jayfunk** [comment]
Just wondering if there are any issues with this pull request? Any questions?

**Comment by jensarps** [comment]
Argh, sorry for the delay, I'm super behind w/ everything atm :/

The PR is great, also matches the `upsertBatch` behavior for an empty array.

So, many thanks for the PR, and thanks for including tests!!

Will merge this.

**Comment by jayfunk** [comment]
I totally understand being busy! Thanks for taking the time to make a great
library. I love giving back to something that has saved me so much effort!

**Comment by jensarps** [comment]
Thanks, and glad that it saved an hour or two!

**Pull request merged**
