### PR TITLE
improved error handling at startup

### LINKED ISSUE #78: error handling if browser does not allow access to databases
It is possible to disable "Allow websites caches and databases" e.g. in IE11. 

If databases are disabled `this.idb` is `null`. This should be handled in [the `openDB` function](https://github.com/jensarps/IDBWrapper/blob/develop/idbstore.js#L252).

### PR DESCRIPTION
**Pull request by mojoaxel**
Check if idb implementation is availible. If not throw error.

fixes #78

### CODE REVIEW

**Comment by jensarps** [comment]
Perfect, thanks for the PR! This will be merged and part of v1.7.2

**Comment by mojoaxel** [comment]
@jensarps You propably forgot to merge this before releasing v1.7.2 :cry: 
Why not just merge ist now and release it later?

**Comment by jensarps** [comment]
Oh noes, I have no idea why this didn't make it into v1.7.2 😕 Really sorry about that...

I won't be able to do another release for at least two weeks, but, I'll merge this into master right now.

**Comment by jensarps** [comment]
I'll leave this open until it's part of a release.

**Pull request merged**
